### ISSUE TITLE
markdown cms - switch all static content to 1 repo/folder

### ISSUE THREAD

**Issue by JamesClonk** [jamesclonk-io/jcio-frontend#14]
- [x] add `config.json` to main folder (contains main config/general settings for displaying jcio static content)
- [x] add `navigation.json` to main folder (contains data on how to setup the navbar, which cms folder goes where, etc..)
- [x] change internal data struct to be more efficient, to make more sense given the new sitatuion.
- [x] use already preparsed `template.HTML` strings in internal data struct, so markdown parsing happens only on a data refresh.
- [x] ~~refresh data only once per 24h~~
- [x] ~~refresh data in a separate, non-blocking goroutine (secured by mutex lock)~~
- [x] only have 1 general refresh url route, `/refresh`
- [x] add ability to read from local folder structure directly too. (will make dev. work *.json config files easier)
- [x] move much of this cms functionality into **stdlib**
