### ISSUE TITLE
add integration-tests to travis-ci

### ISSUE THREAD

**Issue by JamesClonk** [jamesclonk-io/jcio-frontend#16]
- [x] integration tests running on staging env (docker@DO droplet, or app@nova?)
- [x] scrape news, check for expected results
- [x] scrape 101, check for expected results
- [ ] scrape goty, check for expected results
- [x] scrape 404
- [x] scrape error
- [ ] test /refresh
