### ISSUE TITLE
newsreader changes

### ISSUE THREAD

**Issue by JamesClonk** [jamesclonk-io/jcio-frontend#22]
- [x] enforce ordering of news feeds
- [x] intelligent ordering: by len(items) desc, by id asc
- [x] add new id field to feed struct to identify feeds for ordering
- [x] maybe even allow for len(items) ordering variance of 1-2 items?
- [x] show num of items on feeds panel-title
- [x] show total num of items (or feeds?) on newsreader panel-title
